version: "3.8"
services:
  frontend:
    image: construction-frontend
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    command: npm run dev -- --host
    depends_on:
      - backend
    environment:
      - VITE_REACT_APP_BACKEND_URL
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env

  backend:
    image: construction-backend
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - "3005:3005"
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://mongodb/construction"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend:/app
      - /app/node_modules
      - ./backend/gloud.json:/app/gloud.json

  mongodb:
    image: mongo:4.2
    ports:
      - "37017:27017"
    volumes:
      - ./data:/data/db
